[ranks]



[ranks.vip]
#this will give a short and snappy description for the users
#allows for the user to know what they are buying before purchase
description="has vip power access"
mColour=[48,5,11] # used inside the users (aka anywhere the rank decor is displayed)
sColour=[38,5,16] # used inside the users (aka anywhere the rank decor is displayed)
signature="V" # used inside the users (aka anywhere the rank decor is displayed)
manage_ranks=["admin", "moderator"]
